### ISSUE TITLE
Song Download hardstuck at 99%

### ISSUE THREAD

**Issue by Sl0wN** [Zingabopp/BeatSaberMultiplayer#31]
I have got the problem that if i'm joining a room where a map is played that i don't have, i can't download the map completely and get stuck at 99% while the memberboard on the left say's that the download is complete but at the middle screen it clearly say's for examble: 3/4 Players ready. As far as i can say i am the only person with this issue in my clique and it is very pitty that i can't play in multiplayer with anyone. I will try to get some screenshots oft the issue, but there will be nothing to see more than i already explained.
I hope that this is a bug or something and not that im some kind of shittard that is to dump to get it properly installed.

**Comment by Zingabopp** [comment]
Are you using regular Multiplayer with avatars or MultiplayerLite? Thought I fixed that in the latest release. Your download probably isn't actually stuck at 99%, this usually happens when the song was deleted from Beat Saver and the progress bar wasn't resetting back to 0% from the last song downloaded. If that's the case, likely your other friends already had the song from before it was deleted.

If you are on MultiplayerLite's latest version, post your 'Beat Saber\Logs\_latest.log' after you encounter this issue again.

**Comment by Sl0wN** [comment]
So i played a while with a friend and it got better, but the bug still is a thing. Here i got the log file from the plugin, i hope it helps.
[_latest.log](https://github.com/Zingabopp/BeatSaberMultiplayer/files/4512697/_latest.log)

**Comment by Zingabopp** [comment]
Thanks, did it break when you were trying to play Overkill or on the next song?

**Comment by Zingabopp** [comment]
If you can sometime soon, give this build a try. I made the logging more detailed so I can hopefully narrow down the problem. https://github.com/Zingabopp/BeatSaberMultiplayer/suites/617030871/artifacts/4812022

Also, the full game log in the Logs folder (instead of just MultiplayerLite's) would be more helpful since sometimes exceptions aren't caught by the mod and get printed by Unity.

I'll probably rewrite most of the downloader when I have time cause right now the code is pretty spaghetti.

**Comment by Sl0wN** [comment]
[_latest.log](https://github.com/Zingabopp/BeatSaberMultiplayer/files/4516000/_latest.log)
The problem appeared again as we tryed to play "R4V3 B0Y" from the Mapper "Rigid", which is a pretty new map. Overkill and the other maps we played, which weren't that much, caused no problems. I can't tell what makes some maps to produce errors and some not. I hope this is the correct logfile.

**Comment by Zingabopp** [comment]
That was very helpful, this actually looks like a bug in SongCore where it's not finishing reloading your songs. Can you try setting the launch option `--debug` for Beat Saber ([Instructions Here](https://support.steampowered.com/kb_article.php?ref=1040-JWMT-2947)) and running the game with this build of SongCore and sending me the log again. You don't have to play a song, just go into the menu and wait for the songs to finish loading. 
[SongCore.zip](https://github.com/Zingabopp/BeatSaberMultiplayer/files/4517749/SongCore.zip)

**Comment by Zingabopp** [comment]
I asked SongCore's dev about it, he said one of your folders is corrupted: `D:\Steam\steamapps\common\Beat Saber\Beat Saber_Data\CustomLevels\6691 Surf Zapping - Yun0`. It likely has a space at the end or something like that. If you can delete that folder everything should work.

**Comment by Sl0wN** [comment]
So thats a real bummer because i can't delete it, no matter what i do.

/edit: so i got deleted every map that were corrupted with beatlist and the IPA gives no error message for the first time, also it loaded much more maps than i thought i have, but to be sure that it isn't a bug as well i used the SongCore you posted earlyer and i tryed to set the -condebug launch option. This is the Log from the last Loading.
[_latest.log](https://github.com/Zingabopp/BeatSaberMultiplayer/files/4517954/_latest.log)

**Comment by Zingabopp** [comment]
Yeah, that log looks clean. I saw from the previous one Multiplayer had downloaded the same song at least 3 times, hopefully everything should work for you now.
